name: Code Analysis
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coding-standard:
    name: Magento Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-coding-standard/8.3@master
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#        Is not working because of a bug in extdn/github-actions-m2/magento-phpstan/8.1 Dockerfile
#      - uses: extdn/github-actions-m2/magento-phpstan/8.1@master
#        with:
#          composer_name: pushonltd/module-sales-rule-extended-groups
#          phpstan_level: '8'
#          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
#        Is not working because of a bug in extdn/github-actions-m2/magento-phpstan/8.2 Dockerfile
#      - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
#        with:
#          composer_name: pushonltd/module-sales-rule-extended-groups
#          phpstan_level: '8'
#          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        with:
          composer_name: pushonltd/module-sales-rule-extended-groups
          phpstan_level: '8'
          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
      - uses: extdn/github-actions-m2/magento-phpstan/8.4@master
        with:
          composer_name: pushonltd/module-sales-rule-extended-groups
          phpstan_level: '8'
          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
