name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Unit tests - 2.4.5-p12 & PHP 8.1"
        uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        with:
          magento_version: 2.4.5-p12
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups
      - name: "Unit tests - 2.4.6-p10 & PHP 8.2"
        uses: extdn/github-actions-m2/magento-unit-tests/8.2@master
        with:
          magento_version: 2.4.6-p10
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups
      - name: "Unit tests - 2.4.7-p5 & PHP 8.3"
        uses: extdn/github-actions-m2/magento-unit-tests/8.3@master
        with:
          magento_version: 2.4.7-p5
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: "Integration tests - 2.4.5-p12 & PHP 8.1"
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          magento_version: 2.4.5-p12
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups
      - name: "Integration tests - 2.4.6-p10 & PHP 8.2"
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          magento_version: 2.4.6-p10
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups
      - name: "Integration tests - 2.4.7-p5 & PHP 8.3"
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        with:
          magento_version: 2.4.7-p5
          module_name: PushON_SalesRuleExtendedGroups
          composer_name: pushonltd/module-sales-rule-extended-groups
